version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: codemirror
    versions:
    - 5.59.2
    - 5.59.3
    - 5.59.4
    - 5.60.0
  - dependency-name: svelte
    versions:
    - 3.31.2
    - 3.32.1
    - 3.32.3
    - 3.34.0
    - 3.35.0
  - dependency-name: sirv-cli
    versions:
    - 1.0.10
